### ISSUE TITLE
大佬，请教一个问题

### ISSUE THREAD

**Issue by KnowSky404** [Henryhaohao/Slider_Captcha_Crack#1]
就是问一下，做这个算法的时候还用训练学习吗
就是对算法进行训练，还用不用？

**Comment by Henryhaohao** [comment]
不用了,这个网站没有像极验那样运用深度学习对你的轨迹结果进行检测 , 只是简单地检测一下 ;
 所有我也只用了加速度随机一下, 并没有涉及到训练集 @LittleControl

**Comment by KnowSky404** [comment]
@Henryhaohao 
嗯嗯，明白了，十分感谢

**Comment by Henryhaohao** [comment]
没事哦 ! 忘了设置邮箱提醒了,这么长时间才回你,不好意思 ; 
 感谢支持~~哈哈 @LittleControl

**Comment by KnowSky404** [comment]
嗯嗯，没事没事。，我也是一个小白，还要多向大佬学习
@Henryhaohao

**Comment by Henryhaohao** [comment]
OK, 一起努力加油吧 ! @LittleControl
